### PR TITLE
[GH-13968] Add `"skip_slack_parsing"` to PostActionIntegrationResponse.

### LINKED ISSUE #13968: slack-compatibility-layer seems to break results of MM-only interactive-message-button response
Turns out: What happened to slash command responses, #12702 happens to interactive message buttons too :/

So here we go again...

#### Summary
When replying `ephemeral_text` as a result of an interactive message button, the slack-compatibility-layer will break the result as same as slash command responses did: #12702

#### Steps to reproduce
1: create a message with a button.
``{"attachments":[{"actions": [{ "name":"text", "integration": {"url": self.URL+"/interactive", "context": {"action": "show_spoiler", "spoiler":" a < a | b >  a "}}  }]  }]}``
(full code: https://git.somenet.org/pub/jan/mattermost.git/blob/HEAD:/somebot/modules/CommandSpoiler.py)

2: click on the message button
3: let integration resturn the content of `spoiler`
4: get displayed a broken response

#### Expected behavior
Getting `` a < a | b >  a `` as response.

#### Observed behavior (that appears unintentional) 
Got broken response, see screenshot.

image

#### Possible fixes
add: ``"skip_slack_parsing"`` to PostActionIntegrationResponse and skip slack parsing if true.

I can look into it in the next few days and open a PR...

### PR DESCRIPTION
**Pull request by someone-somenet-org**
#### Summary
Adds `"skip_slack_parsing"` to PostActionIntegrationResponse.

If `true` the Slack-Comparability-Logic will be ignored when processing the `ephemeral_text`-response.

#### Ticket Link
Fixes #13968
https://mattermost.atlassian.net/browse/MM-22825

### CODE REVIEW

**Comment by someone-somenet-org** [comment]
Unsure how to test, as you dont seem to have any tests for `ephemeral_text`-responses at all?

I tested it manually here: https://github.com/someone-somenet-org/mattermost-dev-env

screen_20200303_013354

**Comment by someone-somenet-org** [comment]
Related docs mention: https://github.com/mattermost/docs/pull/3427

**Comment by someone-somenet-org** [comment]
:shipit:

File: app/integration_action.go [hunk 1]
```diff
@@ -244,6 +244,11 @@ func (a *App) DoPostActionWithCookie(postId, actionId, userId, selectedOption st
 			RootId:    rootPostId,
 			UserId:    userId,
 		}
+
+		if response.SkipSlackParsing {
```
Comment (iomodo) [inline app/integration_action.go]: I would love to have this `if` little bit higher, so we will not call `model.ParseSlackLinksToMarkdown` when not needed.

**Comment by someone-somenet-org** [comment]
> Also can we add some tests as well?

as i commented earlier: `Unsure how to test, as you dont seem to have any tests for ephemeral_text-responses at all?`

If I did not miss anything, Ill look into writing some ... I cant seem to test usefully in a vagrant vm locally :/

File: app/integration_action.go (hunk 1 above)
Comment (mickmister) [reply app/integration_action.go]: +1 on the second version you propose @someone-somenet-org

**Comment by mickmister** [comment]
Regarding tests, that is quite a large function.

@someone-somenet-org If there is a spot in the function's test that makes sense to add a test, then I would add it. Otherwise it's your call whether you want to add a test.

File: app/integration_action.go (hunk 1 above)
Comment (iomodo) [reply app/integration_action.go]: Duplication is a bad idea, second one is way better, but what you can do is first check the `response.SkipSlackParsing` to initialize just the message and after that initialize the response with the correct message.

**Comment by someone-somenet-org** [comment]
> @someone-somenet-org If there is a spot in the function's test that makes sense to add a test, then I would add it. Otherwise it's your call whether you want to add a test.

If its not a show stopper, I would like to kindly decline.

File: app/integration_action.go (hunk 1 above)
Comment (someone-somenet-org) [reply app/integration_action.go]: adapted. see new commit.

Comment (iomodo) [reply app/integration_action.go]: @someone-somenet-org this is clearly better. I don't want to be a pain, but I don't like `Post` object been half-baked on creation. What do you think about something like this?
```go
message := response.EphemeralText
if !response.SkipSlackParsing {
	message = model.ParseSlackLinksToMarkdown(message)
}
ephemeralPost := &model.Post{
	Message:   message,
	ChannelId: upstreamRequest.ChannelId,
	RootId:    rootPostId,
	UserId:    userId,
}
```

Comment (someone-somenet-org) [reply app/integration_action.go]: This looks ugly imho. I dont like to create new vars if it can be obviously avoided. Also it imho adds visual complexity where there isnt.

What about... ?
 ```go
 ephemeralPost := &model.Post{
 	Message:   response.EphemeralText,
 	ChannelId: upstreamRequest.ChannelId,
 	RootId:    rootPostId,
 	UserId:    userId,
 }

 if !response.SkipSlackParsing {
 	ephemeralPost.message = model.ParseSlackLinksToMarkdown(response.EphemeralText)
 }
 ```

Comment (iomodo) [reply app/integration_action.go]: Way better, thanks @someone-somenet-org 👍

**Comment by mickmister** [comment]
@iomodo What is your current stance on approval of this PR?

**Comment by iomodo** [comment]
@mickmister, waiting for the changes proposed by @someone-somenet-org

**Comment by someone-somenet-org** [comment]
Not sure, why the tests would fail because of the last change change :/

**Comment by someone-somenet-org** [comment]
Without any change by me: suddenly the postgres and distributed textfile editor (mysql) run fine.

It fails somewhere else, but I consider that another circleCI-issue for now. :)

**Comment by someone-somenet-org** [comment]
Nothing changed. now it tests correctly ^.^

File: app/integration_action.go (hunk 1 above)
Comment (someone-somenet-org) [reply app/integration_action.go]: done, I guess.

**Comment by prapti** [comment]
@someone-somenet-org I'm trying to test this PR but not getting the payload to work quite right. In your original steps to reproduce the issue, you've mentioned the payload with `"url": self.URL+"/interactive"`. Could you please help identify what the `self.URL` is so I can reproduce and test it. Thank you so much!

**Comment by prapti** [comment]
@someone-somenet-org Also, does the bot need to be installed in the server for it to work properly?

**Comment by someone-somenet-org** [comment]
> @someone-somenet-org I'm trying to test this PR but not getting the payload to work quite right. In your original steps to reproduce the issue, you've mentioned the payload with `"url": self.URL+"/interactive"`. Could you please help identify what the `self.URL` is so I can reproduce and test it. Thank you so much!

I basically tested it with this script.
https://github.com/someone-somenet-org/mattermost-dev-env/blob/master/test_GH-13968.sh

**Comment by saturninoabril** [comment]
@hanzei Is this for v5.22? Just asking since the ticket is not specifically assigned - https://mattermost.atlassian.net/browse/MM-22825.  Feel free to merge in case it is.  Assigning this PR to you.

**Comment by hanzei** [comment]
@saturninoabril Yes it is. The docs are already merged, hence I'm also merging this small change.
