### PR TITLE
MM-11697: Environment overrides do not overwrite config.json on save

### LINKED ISSUE #10388: [Help Wanted] [MM-11697] Environment variable override incorrectly saves back to config.json
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11697)

Environment variable overrides (e.g. MM_SERVICESETTINGS_SITEURL=[http://example.com]) are incorrectly written back to the configuration when it is saved.

Update the config store to maintain a copy of the config loaded without environment variable overrides, and a copy with the variables overridden. Then, when Set() is called, iterate over the known, overridden fields and use the previously loaded values instead. Calling Get() should continue to return a configuration reflecting the “merged” state, with environment variables overriding settings.

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
The config store now keeps a copy of the config as loaded from the store
without environment overrides. Whenever persisting, we now check if the
current setting is different from the loaded setting. If it is, then use
the loaded setting instead.

As described in the comments to `removeEnvOverrides` in `common.go`,
this behavior will have to change if we ever let the user change a
setting that has been environmentally overriden.

This was interesting because the `load` function in `common.go` also
persists, so we have to tee the provided `io.ReadCloser` and construct a
config that doesn't have the environment overrides. And then we have to
find the path to the (maybe) changed variable in the config struct
using reflection.

I didn't deal with slice or map configuration variable types. I don't think those are
easily settable via environment variables (unless you assume a space separated 
string is a slice, for example, and I don't think MM is doing that, correct?).

Possible WIP: I had to expose a `GetWithoutEnvOverrides` function in the
Store interface just for the tests -- this is because the `file_test`
and `database_test`s are in the `config_test` package instead of the
`config` package.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-11697
Fixes #10388

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by lieut-data** [comment]
Sorry for the thrashing changes in `config`, @cpoile, but I've just merged the last of the config rework. Can you take a look and merge in `master` with your changes?

**Comment by cpoile** [comment]
@lieut-data No problem, done!

File: config/common.go [hunk 1]
```diff
@@ -141,3 +174,95 @@ func (cs *commonStore) validate(cfg *model.Config) error {
...
+	return newCfg
+}
+
+// getPaths is helper function for removeEnvOverrides
+func getPaths(m map[string]interface{}) [][]string {
+	return getPathsRec(m, nil, nil)
+}
+
+// getPathsRec is helper function for removeENvOverrides
+func getPathsRec(src interface{}, curPath []string, allPaths [][]string) [][]string {
```
Comment (lieut-data) [inline config/common.go]: nit: rather than passing in `allPaths` onto which we accumulate (but never read inside this method), I believe this function could just return its view of `allPaths` and let the parent call accumulate, making for a simpler recursive model:

```go
func getPathsRec(src interface{}, curPath []string) [][]string {
	if reflect.ValueOf(src).Kind() == reflect.Map {
		paths := [][]string{}
		for k, v := range src.(map[string]interface{}) {
			paths = append(paths, getPathsRec(v, append(curPath, k))
		}
		return paths
	}

	return [][]string{curPath}
}
```

Comment (lieut-data) [reply config/common.go]: Secondly, I think the `reflect.ValueOf` might be better captured as a cast attempt instead, given we cast to an even more strict type anyway:
```go
	if srcMap, ok := src.(map[string]interface{}); ok {
		paths := [][]string{}
		for k, v := range srcMap {
			paths = append(paths, getPathsRec(v, append(curPath, k))
		}
		return paths
	}
```

File: config/common.go [hunk 2]
```diff
@@ -141,3 +174,95 @@ func (cs *commonStore) validate(cfg *model.Config) error {
...
+		val = val.Elem()
+	}
+	if val.Kind() == reflect.Struct {
+		return getVal(val.Interface(), path[1:])
+	}
+	return val
+}
+
+// setVal is helper function for removeENvOverrides
+func setVal(tgt interface{}, path []string, newVal interface{}) {
```
Comment (lieut-data) [inline config/common.go]: Could this method be replaced by a call to [Value.Set](https://golang.org/pkg/reflect/#Value.Set) instead?

File: config/common.go [hunk 3]
```diff
@@ -141,3 +174,95 @@ func (cs *commonStore) validate(cfg *model.Config) error {
 
 	return nil
 }
+
+// removeEnvOverrides returns a new config without the current environment overrides.
+// If a config variable has an environment override, that variable is set to the value that was
+// read from the store.
+func (cs *commonStore) removeEnvOverrides(cfg *model.Config) *model.Config {
```
Comment (lieut-data) [inline config/common.go]: Given your pending work on a `mergeConfig(cfg1, cfg2 *model.Config) *model.Config`, I'm wondering if we could reuse that method here instead. It would mean having to represent `*model.Config` of /only/  the values that were /not/ overridden, so that we could force them back on before `persist`. 

Maybe building /that/ struct amounts to the same amount of work, so 0/5 right now, given that this implementation detail is entirely abstracted within the package.

File: config/common.go [hunk 4]
```diff
@@ -86,44 +98,65 @@ func (cs *commonStore) set(newCfg *model.Config, validate func(*model.Config) er
...
 
 	loadedCfg.SetDefaults()
+	loadedCfgNoEnv.SetDefaults()
 
 	if validate != nil {
 		if err = validate(loadedCfg); err != nil {
-			return errors.Wrap(err, "invalid config")
+			return errors.Wrap(err, "invalid config with env overrides")
+		}
+		if err = validate(loadedCfgNoEnv); err != nil {
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/common.go]: Excellent point. I was able to remove almost everything after that first load of loadedCfgWithoutEnvOverrides (new line 103).

File: config/common.go [hunk 5]
```diff
@@ -86,44 +98,65 @@ func (cs *commonStore) set(newCfg *model.Config, validate func(*model.Config) er
...
 	}
+	if changed := fixConfig(loadedCfgNoEnv); changed {
+		needsSave = true
+	}
 
 	cs.configLock.Lock()
 	var unlockOnce sync.Once
 	defer unlockOnce.Do(cs.configLock.Unlock)
 
+	oldCfg := cs.config
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/common.go]: Yes, that's a much nicer solution! 
I had to attach one function (removeEnvOverrides, new line 169) so that we can get at the commonStore's variables when we call it in the Set function, and the tests. The rest of the helpers (not attached to commonStore) are still below, is that the preferred organization?

File: config/common.go (hunk 3 above)
Comment (cpoile) [reply config/common.go]: I investigated using the merge, but in the end I think it might be too complicated. First, you're right -- it basically is the same amount of work to create a blank config with only the envOverrides set. But then we'd also have to be very sure that none of the values in an empty config struct are set to their zero values (and I noticed that not /every/ variable is a pointer, which means we'd want to check if they had changed and keep track before/after the merge, just to be safe).

File: config/common.go (hunk 1 above)
Comment (cpoile) [reply config/common.go]: Excellent rewriting of getPathsRec (as I mentioned over coffee).  And the cast attempt is much cleaner, thanks!

File: config/common.go (hunk 2 above)
Comment (cpoile) [reply config/common.go]: Yep. I could just eliminate that whole method because it was simplified so much. Thanks!

File: config/database_test.go [hunk 6]
```diff
@@ -415,6 +415,28 @@ func TestDatabaseStoreLoad(t *testing.T) {
...
+		err = ds.Load()
+		require.NoError(t, err)
+		_, err = ds.Set(ds.Get())
+		require.NoError(t, err)
+		err = ds.Load()
+		require.NoError(t, err)
+
+		assert.Equal(t, "http://override", *ds.Get().ServiceSettings.SiteURL)
+		assert.Equal(t, map[string]interface{}{"ServiceSettings": map[string]interface{}{"SiteURL": true}}, ds.GetEnvironmentOverrides())
+		assert.Equal(t, "http://minimal", *ds.GetWithoutEnvOverrides().ServiceSettings.SiteURL)
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/database_test.go]: I tried to do this (line 460 in file_test.go), but it turns out that when loading from the path, the returned config file is not exactly the same. Empty slices in the config are unmarshaled as nil by Viper, and some (all?) deprecated settings are saved as nil, and one setting's defaults (GlobalRelaySettings) look like they are persisted to the file but not changed in the fs config. Here's the diff:

--- expected (the fs.Get() config struct)
+++ Actual (the unmarshaled config from the path)
```
        	            	@@ -403,6 +398,6 @@
            	            	   GlobalRelaySettings: (*model.GlobalRelayMessageExportSettings)({
            	            	-   CustomerType: (*string)(<nil>),
            	            	-   SmtpUsername: (*string)(<nil>),
            	            	-   SmtpPassword: (*string)(<nil>),
            	            	-   EmailAddress: (*string)(<nil>)
            	            	+   CustomerType: (*string)((len=2) "A9"),
            	            	+   SmtpUsername: (*string)(""),
            	            	+   SmtpPassword: (*string)(""),
            	            	+   EmailAddress: (*string)("")
```
So for now I'm just doing a simple check. Do you want me to look into these other issues?

File: config/file_test.go [hunk 7]
```diff
@@ -436,6 +436,28 @@ func TestFileStoreLoad(t *testing.T) {
...
+		err = fs.Load()
+		require.NoError(t, err)
+		_, err = fs.Set(fs.Get())
+		require.NoError(t, err)
+		err = fs.Load()
+		require.NoError(t, err)
+
+		assert.Equal(t, "http://override", *fs.Get().ServiceSettings.SiteURL)
+		assert.Equal(t, map[string]interface{}{"ServiceSettings": map[string]interface{}{"SiteURL": true}}, fs.GetEnvironmentOverrides())
+		assert.Equal(t, "http://minimal", *fs.GetWithoutEnvOverrides().ServiceSettings.SiteURL)
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/file_test.go]: see above

File: config/store.go [hunk 8]
```diff
@@ -17,6 +17,10 @@ type Store interface {
 	// Get fetches the current, cached configuration.
 	Get() *model.Config
 
+	// GetWithoutEnvOverrides fetches the current, cached configuration without environment variables
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/store.go]: That is great, I had no idea you could do that. Thanks!

File: config/common.go [hunk 9]
```diff
@@ -140,3 +156,75 @@ func (cs *commonStore) validate(cfg *model.Config) error {
 
 	return nil
 }
+
+// mergeConfig merges two configs together. The receiver's values are overwritten with the patch's
```
Comment (lieut-data) [inline config/common.go]: See upstream, but we can just use the public `MergeConfig` vs. needing a version on the store.

File: config/common.go [hunk 10]
```diff
@@ -140,3 +156,75 @@ func (cs *commonStore) validate(cfg *model.Config) error {
...
+	if err != nil {
+		return nil, err
+	}
+	retC := ret.(model.Config)
+	return &retC, nil
+}
+
+// removeEnvOverrides takes the newCfg provided and adds information stored in the commonStore,
+// then delegates the task to the removeEnvOverrides function
+func (cs *commonStore) removeEnvOverrides(newCfg *model.Config) *model.Config {
```
Comment (lieut-data) [inline config/common.go]: nit: `new` in `newCfg` is confusing here -- it's probably clearer to just name this `cfg`?

File: config/common.go [hunk 11]
```diff
@@ -140,3 +156,75 @@ func (cs *commonStore) validate(cfg *model.Config) error {
...
+	return removeEnvOverrides(newCfg, cs.configWithoutOverrides, cs.environmentOverrides)
+}
+
+// removeEnvOverrides returns a new config without the current environment overrides.
```
Comment (lieut-data) [inline config/common.go]: `s/current/given`

File: config/common.go [hunk 12]
```diff
@@ -140,3 +156,75 @@ func (cs *commonStore) validate(cfg *model.Config) error {
...
+// If a config variable has an environment override, that variable is set to the value that was
+// read from the store.
+func removeEnvOverrides(cfg, cfgWithoutEnv *model.Config, envOverrides map[string]interface{}) *model.Config {
+	paths := getPaths(envOverrides)
+	newCfg := cfg.Clone()
+	for _, path := range paths {
+		currentVal := getVal(newCfg, path)
+		originalVal := getVal(cfgWithoutEnv, path)
+		if currentVal.Interface() != originalVal.Interface() {
```
Comment (lieut-data) [inline config/common.go]: Could we just /always/ `newVal.Set`? Presumably this will almost always be true, unless we happened to override to the existing configuration value, which seems unlikely.

File: config/common.go (hunk 11 above)
Comment (lieut-data) [reply config/common.go]: Also, propose moving this and below into another file, perhaps `environment.go`?

File: config/common.go (hunk 9 above)
Comment (cpoile) [reply config/common.go]: Huh, I didn't see that it had been moved and merged it accidentally. Oops! :)

File: config/common.go (hunk 11 above)
Comment (cpoile) [reply config/common.go]: Good idea. Is there a MM style guide to help with deciding when to split off functions, and how (eg, preferred length of files)? 

For this, I put all the functions in `environment.go` but kept the commonStore method in `common.go`.

File: config/common.go (hunk 12 above)
Comment (cpoile) [reply config/common.go]: ...Right, I think you're right. The only time we would _not_ want to replace a config value, is if the user changed the config value manually. And since we don't allow them to change config values that are overridden by the environment, that can't happen. Correct?

Q: why don't we allow them to change variables that have been set through the environment? Are MM instances running for weeks/months/years? If so, it seems like it's a bit of an inconvenience, no?

File: config/file_test.go [hunk 13]
```diff
@@ -436,6 +436,31 @@ func TestFileStoreLoad(t *testing.T) {
...
+		path, tearDown := setupConfigFile(t, minimalConfig)
+		defer tearDown()
+
+		fs, err := config.NewFileStore(path, false)
+		require.NoError(t, err)
+		defer fs.Close()
+
+		assert.Equal(t, "http://minimal", *fs.Get().ServiceSettings.SiteURL)
+
+		os.Setenv("MM_SERVICESETTINGS_SITEURL", "http://override")
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/file_test.go]: I was wrong to Set first: there's no point, since the env variable doesn't have a chance to override until Load. Should have called it after. 

But, I'm pretty sure line 447 checks that the environment override isn't being persisted from the prior test. Either way, I'll make it unambiguous by make the env variable unique for this test -- good idea. And I'll move it to before the file store. (I'll do that for the previous test as well.)  Now there's no reason call load a second time at all.

File: config/file_test.go [hunk 14]
```diff
@@ -436,6 +436,31 @@ func TestFileStoreLoad(t *testing.T) {
...
+
+		_, err = fs.Set(fs.Get())
+		require.NoError(t, err)
+		err = fs.Load()
+		require.NoError(t, err)
+
+		assert.Equal(t, "http://override", *fs.Get().ServiceSettings.SiteURL)
+		assert.Equal(t, map[string]interface{}{"ServiceSettings": map[string]interface{}{"SiteURL": true}}, fs.GetEnvironmentOverrides())
+		assert.Equal(t, "http://minimal", *config.GetConfigWithoutOverridesFS(fs).ServiceSettings.SiteURL)
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/file_test.go]: It looks like loading up the file directly from disk causes the same problem as assertFileEqualsConfig (see the diff).

I think the test with the exported GetConfigWithoutOverrides does what we want, if we assume that the when we persist we are calling that same function. That's an assumption that we're not testing here.  I'm open to any thoughts on how to bridge that.   I'm happy to go deeper into the persist and unmarshal code to see how we can make the file exactly equal the commonStore's config.

 Here's diff between the two. Looks like the deprecated settings aren't persisted, and the empty slices are being persisted as nil. 

```
   --- Expected
   +++ Actual
   @@ -12,4 +12,3 @@
      TLSStrictTransportMaxAge: (*int64)(63072000),
   -  TLSOverwriteCiphers: ([]string) {
   -  },
   +  TLSOverwriteCiphers: ([]string) <nil>,
      UseLetsEncrypt: (*bool)(false),
   @@ -26,3 +25,3 @@
      EnableCommands: (*bool)(true),
   -  DEPRECATED_DO_NOT_USE_EnableOnlyAdminIntegrations: (*bool)(true),
   +  DEPRECATED_DO_NOT_USE_EnableOnlyAdminIntegrations: (*bool)(<nil>),
      EnablePostUsernameOverride: (*bool)(false),
   @@ -56,5 +55,5 @@
      GfycatApiSecret: (*string)((len=64) "3wLVZPiswc3DnaiaFoLkDvB4X0IV6CpMkj4tf2inJRsBY6-FnkT08zGmppWFgeof"),
   -  DEPRECATED_DO_NOT_USE_RestrictCustomEmojiCreation: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPostDelete: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_AllowEditPost: (*string)((len=6) "always"),
   +  DEPRECATED_DO_NOT_USE_RestrictCustomEmojiCreation: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPostDelete: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_AllowEditPost: (*string)(<nil>),
      PostEditTimeLimit: (*int)(-1),
   @@ -88,3 +87,3 @@
      MaxUsersPerTeam: (*int)(50),
   -  DEPRECATED_DO_NOT_USE_EnableTeamCreation: (*bool)(true),
   +  DEPRECATED_DO_NOT_USE_EnableTeamCreation: (*bool)(<nil>),
      EnableUserCreation: (*bool)(true),
   @@ -97,10 +96,10 @@
      RestrictDirectMessage: (*string)((len=3) "any"),
   -  DEPRECATED_DO_NOT_USE_RestrictTeamInvite: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPublicChannelManagement: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelManagement: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPublicChannelCreation: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelCreation: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPublicChannelDeletion: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelDeletion: (*string)((len=3) "all"),
   -  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelManageMembers: (*string)((len=3) "all"),
   +  DEPRECATED_DO_NOT_USE_RestrictTeamInvite: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPublicChannelManagement: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelManagement: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPublicChannelCreation: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelCreation: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPublicChannelDeletion: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelDeletion: (*string)(<nil>),
   +  DEPRECATED_DO_NOT_USE_RestrictPrivateChannelManageMembers: (*string)(<nil>),
      EnableXToLeaveChannelsFromLHS: (*bool)(false),
   @@ -116,4 +115,3 @@
      ExperimentalPrimaryTeam: (*string)(""),
   -  ExperimentalDefaultChannels: ([]string) {
   -  }
   +  ExperimentalDefaultChannels: ([]string) <nil>
     },
   @@ -130,6 +128,4 @@
      DataSource: (*string)((len=105) "mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"),
   -  DataSourceReplicas: ([]string) {
   -  },
   -  DataSourceSearchReplicas: ([]string) {
   -  },
   +  DataSourceReplicas: ([]string) <nil>,
   +  DataSourceSearchReplicas: ([]string) <nil>,
      MaxIdleConns: (*int)(20),
   @@ -244,4 +240,3 @@
      AllowCustomThemes: (*bool)(true),
   -  AllowedThemes: ([]string) {
   -  }
   +  AllowedThemes: ([]string) <nil>
     },
   @@ -431,4 +426,3 @@
     DisplaySettings: (model.DisplaySettings) {
   -  CustomUrlSchemes: ([]string) {
   -  },
   +  CustomUrlSchemes: ([]string) <nil>,
      ExperimentalTimezone: (*bool)(false)
Test: TestFileStoreLoad/do_not_persist_environment_variables
```

File: config/export_test.go [hunk 15]
```diff
@@ -26,3 +26,18 @@ func InitializeConfigurationsTable(db *sqlx.DB) error {
 func ResolveConfigFilePath(path string) (string, error) {
 	return resolveConfigFilePath(path)
 }
+
+// GetCommonStore exposes the internal commonStore to test only.
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/export_test.go]: I think I merged that by accident when updating to master -- you're right, we don't need it anymore.

File: config/export_test.go [hunk 16]
```diff
@@ -26,3 +26,18 @@ func InitializeConfigurationsTable(db *sqlx.DB) error {
...
+func (ms *memoryStore) MergeConfig(patch *model.Config) (*model.Config, error) {
+	return ms.mergeConfig(patch)
+}
+
+// GetWithoutEnvOverrides exposes the internal
```
[the remark this answers is not in the document]
Comment (cpoile) [reply config/export_test.go]: See comments below -- I agree, I think it's cleaner, but I'll have to go deeper into how we unmarshal the config before we can do that.

**Comment by cpoile** [comment]
Thanks @lieut-data! 

I made the changes, except I'm having trouble with the `getActualFileConfig` (same problem with `getActualDatabaseConfig`).

File: config/file_test.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (lieut-data) [reply config/file_test.go]: I think it's fine to narrow this test to focus on the not writing to disk part.

File: config/file_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (lieut-data) [reply config/file_test.go]: I agree there will be some differences in the default initialization from `getActualFileConfig`, but could we just do something like:
```go
actualConfig := getActualFileConfig()
assert.Equal(t, "http://minimal", actualConfig.ServiceSettings.SiteURL)
```

True, we won't be verifying the whole file, but we should be able to successfully verify that `SiteURL` wasn't written back to disk, and that without requiring any internal access to the store.

File: config/common.go (hunk 11 above)
Comment (lieut-data) [reply config/common.go]: There probably /should/ be a style guide for this, but I'm honestly just using the force here. It feels like the environment stuff forms a cluster of helper methods that are relatively independent from the common store, and so it might be easier to browse through them in a separate file. It's an incredibly subjective opinion, and I'm 0/5 on it :p

File: config/file_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (cpoile) [reply config/file_test.go]: Ah, so much better. Thanks!  (Kind of ashamed I didn't think of that myself...)

**Comment by cpoile** [comment]
@lieut-data Thanks, updated!

File: config/database_test.go [hunk 17]
```diff
@@ -415,6 +417,28 @@ func TestDatabaseStoreLoad(t *testing.T) {
...
+		require.NoError(t, err)
+		defer ds.Close()
+
+		_, err = ds.Set(ds.Get())
+		require.NoError(t, err)
+
+		assert.Equal(t, "http://overridePersistEnvVariables", *ds.Get().ServiceSettings.SiteURL)
+		assert.Equal(t, map[string]interface{}{"ServiceSettings": map[string]interface{}{"SiteURL": true}}, ds.GetEnvironmentOverrides())
+		// check that in memory configWithoutOverrides does not include overwritten variable
+		assert.Equal(t, "http://minimal", *config.GetConfigWithoutOverridesDS(ds).ServiceSettings.SiteURL)
```
Comment (lieut-data) [inline config/database_test.go]: Can we just get rid of `GetConfigWithoutOverridesDS` altogether now? Having verified that the on-disk/in-database state and `Get()` interface state is accurate, the internal implementation details aren't really worth "testing" IMO.

Comment (cpoile) [reply config/database_test.go]: Excellent point, done!

File: config/common.go (hunk 12 above)
Comment (lieut-data) [reply config/common.go]: Conceivably, we could allow a temporary change to the configuration, such that we discard the environment override if set via the system console, but it would unexpectedly come back on restart when the variable is overridden again -- there's no way to know to discard it then.

Environment overrides are primarily intended to be used to tweak server-specific settings -- e.g. changing SiteURL on community-daily.mattermost.com vs community.mattermost.com. They were also used for Docker-like environments, where we also used to have the read-only config, but now that we have the database config, I expect them to be used a lot less frequently.
