### PR TITLE
[MM-15836] Fix redirect after OAuth login

### LINKED ISSUE #10943: redirect_to information not used after gitlab login, breaking oauth provider flow when not logged in yet
When logging in through gitlab (or any other oauth provider), the redirect_to param pointing to the URL to go to after successfully logging in is lost. It's included in the base64-encoded oauth state in `GetOAuthLoginEndpoint`, but never used after completing the oauth login flow. `CompleteOAuth` still receives the state props, but the `redirect_to` value is never used!

---

While this is just a minor annoyance for normal links to mattermost (deep links don't work because of it unless you are already logged in), it breaks things when using Mattermost's OAuth *provider*:

Imagine I go to Awesome App X ("X") which uses Mattermost's OAuth provider to log in.
So I'm redirect to Mattermost during X's oauth flow and presented with its login page. All fine so far. I click on the "GitLab" login button and complete the login. But now, instead of getting the oauth consent screen (or being redirected to the app if already authorized), I end up in mattermost itself. The **only** way to recover here is to manually go back to X and start its oauth flow again (which will now succeed since I'm already logged-in in Mattermost)

### PR DESCRIPTION
**Pull request by ThiefMaster**
#### Summary
This fixes the `redirect_to` value being ignored after logging in via OAuth.

#### Ticket Link
fixes #10943

### CODE REVIEW

**Comment by hmhealey** [comment]
@ThiefMaster Can you base this branch off of master? We'll cherry-pick it onto a release branch after merging based on what version the triage meeting assigns to it

File: api4/oauth.go [hunk 1]
```diff
@@ -530,7 +530,10 @@ func completeOAuth(c *Context, w http.ResponseWriter, r *http.Request) {
 
 		c.App.Session = *session
 
-		redirectUrl = c.GetSiteURLHeader()
+		var ok bool
+		if redirectUrl, ok = props["redirect_to"]; !ok {
```
Comment (hmhealey) [inline api4/oauth.go]: While it's a bit less compact, could you change this around slightly to make it more obvious what's going on here? It took me a few minutes to realize that `redirectUrl` is actually modified in either case here.
```go
if _, ok = props["redirect_to"]; ok {
    redirectUrl = props["redirect_to"]
} else {
    redirectUrl = c.GetSiteURLHeader()
}
```

**Comment by ThiefMaster** [comment]
Sure, the main reason to make it against 5.11 was so I could test it with the webapp from the release package since I really didn't want to download all the deps for webapp over the slow connection here (cloning the serve repo took 80min, I don't want to know how long `npm install` for webapp would have taken ;))

Rebased & changed the PR's branch.

**Comment by hmhealey** [comment]
Good to know. Generally, the web app should work if it's out of sync with the server, even though we don't ensure the same level backwards compatibility that the mobile app and server have

File: api4/oauth.go (hunk 1 above)
Comment (ThiefMaster) [reply api4/oauth.go]: Good point, and it's actually cleaner that way since I can switch to `_, ok := ...` instead of declaring `ok` before.

**Comment by ThiefMaster** [comment]
Updated the code as well.

**Comment by amyblais** [comment]
Is this bug a recent regression?

**Comment by ThiefMaster** [comment]
I think this was always broken.

**Comment by hanzei** [comment]
@amyblais Should this go into 5.13 or 5.14?

**Comment by amyblais** [comment]
v5.13 is fine

**Comment by hanzei** [comment]
@jwilander I'm always confused how to handle this kind of cherry pick situation. Is merging rather sooner then later and cherry picking after the new release branch has been cut the idiomatic way?

**Comment by jwilander** [comment]
Yes so we generally merge right away to avoid having to worry about merge conflicts down the line and also to get it soaking in master soon. Then once the release branch is cut we can do the cherry pick. The only time we would wait to merge is if the next release is going to be based off `master`. Since 5.13 is an odd release it'll be based off `release-5.12` so we can merge to `master` right away.
