### PR TITLE
plugin: fix InstallPlugin() API by manually creating RPC code

### LINKED ISSUE #13040: plugin API: InstallPlugin() does not work
#### Summary
Plugin API is using `net/rpc` to communicate with Mattermost server.

`net/rpc` is using `encoding/gob` to decode/encode Go types. 

`plugin.API.InstallPlugin(r io.Reader, replace bool)` accepts a reader `r` to upload plugin context to Mattermost server through `net/rpc`. But `encoding/gob` seems to not support reader implementations.

`encoding/gob` tries to resolve any interface type to struct type. It also tries to resolve `io.Reader` interface to struct type that implements it. But, it cannot find registers for resolved struct type.

For ex:

**1-** Following error is returned by the rpc call if `io.Reader` is a sample of [cancelTimerBody](https://golang.org/pkg/net/http/?m=all#cancelTimerBody) which is actually `http.Response.Body` and returned while using an http client with a timeout set, like: `response, err := http.Client{Timeout: time.Minute}.Get(pluginURL)`.

```
INFO[2019-11-09T22:10:16.2094998+03:00] 2019/11/09 22:10:16 RPC call to InstallPlugin API failed: gob: type not registered for interface: http.cancelTimerBody  caller="go-plugin/stream.go:15" plugin_id=marketplace-addon source=plugin_stderr
```

**2-**  Following error is returned by the rpc call, if `io.Reader` is a sample of `bytes.Reader`:
```
INFO[2019-11-09T23:31:01.574781+03:00] 2019/11/09 23:31:01 RPC call to InstallPlugin API failed: gob: type not registered for interface: bytes.Reader  caller="go-plugin/stream.go:15" plugin_id=marketplace-addon source=plugin_stderr

```

**3-** You can try the same for other `io.Reader`s like `strings.Reader`, you'll get yet another _gob_ error.

#### Steps to reproduce
Try to use `plugin.API.InstallPlugin()` to install a plugin.

I tested with `v.5.16.1` and the current master `d9a154fc70b39acc7121bdd487f9a81131de1f8f`. Results are the same.

Related RPC level implementation: https://github.com/mattermost/mattermost-server/blob/1db045b/plugin/client_rpc_generated.go#L3620-L3626

#### Expected behavior
Should install plugin.

Please note that, `InstallPlugin()` does not return an error but we get the error from server logs like in the above examples.

#### Possible fixes
I haven't go to deep but had a quick look on the RPC related code. It seems that we use a `muxBroker` and HashiCorp's _yamux_ for TCP multiplexing.

Which means we have a way to directly upload files to server via multiplex connection without need to use RPC.

Plugin Hook API also benefits from that to stream file for [FileWillBeUploaded() hook](https://developers.mattermost.com/extend/plugins/server/reference/#Hooks.FileWillBeUploaded). See client implementation here: https://github.com/mattermost/mattermost-server/blob/428454c/plugin/client_rpc.go#L456-L497

Same solution can be applied to `InstallPlugin()` by not trying to stream the `io.Reader` through RPC but streaming it via a bare multiplex connection. 

One other solution would be changing `InstallPlugin()` API to accept a `[]byte` instead of reader. But this solution is not elegant and it wastes on the memory by pre-loading whole plugin data.

### PR DESCRIPTION
**Pull request by ilgooz**
#### Summary
Previous implementation of **InstallPlugin()**-mattermost#12232 's RPC funcs wasn't working because `io.Reader` isn't supported by the RPC code generation tool.

RPC does not support streaming data and RPC code generation tool does not handle this exception.

Thus, RPC funcs are now implemented manually to stream `io.Reader` through a separate multiplexed connection.

#### Ticket Link
Fixes #13040

/cc @lieut-data @crspeller

### CODE REVIEW

File: app/plugin_api_test.go [hunk 1]
```diff
@@ -731,6 +745,93 @@ func TestPluginAPIInstallPlugin(t *testing.T) {
...
+	th := Setup(t).InitBasic()
+	defer th.TearDown()
+
+	path, _ := fileutils.FindDir("tests")
+	ts := httptest.NewServer(http.FileServer(http.Dir(path)))
+	defer ts.Close()
+	downloadURL := ts.URL + "/testplugin.tar.gz"
+
+	var pluginJson map[string]interface{}
+	err := json.Unmarshal([]byte(fmt.Sprintf(`{"DownloadURL": "%s"}`, downloadURL)), &pluginJson)
```
Comment (lieut-data) [inline app/plugin_api_test.go]: Why `json.Unmarshal` instead of just populating `pluginJson` directly?

File: plugin/client_rpc.go [hunk 2]
```diff
@@ -720,3 +720,54 @@ func (s *apiRPCServer) LogError(args *Z_LogErrorArgs, returns *Z_LogErrorReturns
...
+	_returns := &Z_InstallPluginReturns{}
+	if err := g.client.Call("Plugin.InstallPlugin", _args, _returns); err != nil {
+		log.Print("RPC call InstallPlugin to plugin failed.", mlog.Err(err))
+	}
+
+	return _returns.A, _returns.B
+}
+
+func (g *apiRPCServer) InstallPlugin(args *Z_InstallPluginArgs, returns *Z_InstallPluginReturns) error {
+	receivePluginConnection, err := g.muxBroker.Dial(args.PluginStreamID)
```
[the remark this answers is not in the document]
Comment (ilgooz) [reply plugin/client_rpc.go]: Do yo mean why starting to `Accept()` at the client side instead of doing it in the reverse way? Please correct me if I misunderstood your question. 

I think it's not possible to `Accept()` from the server side without doing some sort of synchronization or other tricks because client won't have any information about if server is ready to accept connections.

```
> [T] app calls: client.InstallPlugin()
  > [T] client.InstallPlugin() calls server.InstallPlugin() with stream-id.
    > [T(+1)]-(network is slower) server receives the call, starts to `Accept()` connections for stream-id.
  > [T(+0.001)]-(goroutine is faster) client tries to `go Dial()` with stream-id but it's most likely server has not started to Accept() yet.
  > [T(+0.5)] client cannot Dial() and thus, cannot send data to server and returns with error.
```

To overcome this, client needs to know when server is ready to `Accept()`. The easiest way would be pooling the `err := Dial()` until `err == nil` but this solution is not elegant.  

--
Although multiplexed connections works in both ways and I think it's common to initialize a connection from both ends since it really depends on scenario.

Also, in the current code, once client starts to accept connections with `Accept()` but if server is unable to `Dial()` for some reason like a network failure during the _RPC_ call initiative from the client _client.RPC("Plugin.InstallPlugin")_, still `Accept()` will be cancelled after [this timeout hits](https://github.com/hashicorp/go-plugin/blob/2543bf2/mux_broker.go#L186) and there will be nothing left out in the memory.

File: app/integration_action_test.go [hunk 3]
```diff
@@ -469,6 +469,7 @@ func TestSubmitInteractiveDialog(t *testing.T) {
 			plugin.ClientMain(&MyPlugin{})
 		}
 		`, `{"id": "myplugin", "backend": {"executable": "backend.exe"}}`, "myplugin", th.App)
+	tearDown()
```
[the remark this answers is not in the document]
Comment (ilgooz) [reply app/integration_action_test.go]: Yes, this one looks a bit weird, it feels like we need to put a defer on it. I totally agree with you, doing the cleanups after the whole Test func is completed makes the most sense.

But I haven't deferred them because I didn't wan't to change the previous behavior where _temp_ dirs gets deleted after `setupPluginApiTest()` returns.

Tho, I tried once deferring it all but I remember that tests did fail and I thought there might be some logic depends on non-deferred use -actually might even be a bug- so I reverted back.

File: app/plugin_api_test.go (hunk 1 above)
Comment (ilgooz) [reply app/plugin_api_test.go]: Oops, totally my bad! I remember that I've just copied this code from the existing tests somewhere. Will be sending a fix commit in a bit.

**Comment by lieut-data** [comment]
@ilgooz, thanks for the updates! Will take a second look at your comments.

In the future, can you avoid force pushing updates? See https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing for the detailed rationale, but in short, it enables incremental reviews, and since we squash on merge anyway, doesn't clutter the history no matter how many changes might be required in the PR.

File: app/integration_action_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (lieut-data) [reply app/integration_action_test.go]: Agreed that there might be some logic that depends on the weird behaviour here. If we end up needing to just call `tearDown()` right away, is there any reason to return the function at all? Why not just continue to teardown in the function itself?

File: app/plugin_api_test.go [hunk 4]
```diff
@@ -51,12 +58,13 @@ func setupMultiPluginApiTest(t *testing.T, pluginCodes []string, pluginManifests
 		require.True(t, activated)
 	}
 
-	app.SetPluginsEnvironment(env)
-
-	return pluginDir
+	return func() {
+		defer os.RemoveAll(pluginDir)
```
Comment (lieut-data) [inline app/plugin_api_test.go]: Note too that the `defer` here is redundant -- it really just reverses the order of these two function calls.

File: plugin/client_rpc.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (lieut-data) [reply plugin/client_rpc.go]: Actually, I'm just wondering if we can test for the `InstallPlugin` to be implemented before setup the stream only they to have to immediately close it:
```go
func (g *apiRPCServer) InstallPlugin(args *Z_InstallPluginArgs, returns *Z_InstallPluginReturns) error {
	hook, ok := g.impl.(interface {
 		InstallPlugin(file io.Reader, replace bool) (*model.Manifest, *model.AppError)
 	}); 
        if !ok {
 		return encodableError(fmt.Errorf("API InstallPlugin called but not implemented."))
        }

	receivePluginConnection, err := g.muxBroker.Dial(args.PluginStreamID)
        // ...

        returns.A, returns.B = hook.InstallPlugin(pluginReader, args.B)
        return nil
}
```

Comment (crspeller) [inline plugin/client_rpc.go]: Instead of going though the complicated process of setting up the streams you could just do what I did for the PluginHTTP and read into buffers and send a byte array: https://github.com/mattermost/mattermost-server/blob/master/plugin/client_rpc.go#L372

Plugin packages are pretty small so it's likely not an issue.

[the remark this answers is not in the document]
Comment (ilgooz) [reply plugin/client_rpc.go]: Oh, of course. I see it know, we should call `Dial()` if there is an implementation for `InstallPlugin ()`.

**Comment by ilgooz** [comment]
> @ilgooz, thanks for the updates! Will take a second look at your comments.
> 
> In the future, can you avoid force pushing updates? See https://developers.mattermost.com/blog/submitting-great-prs/#4-avoid-force-pushing for the detailed rationale, but in short, it enables incremental reviews, and since we squash on merge anyway, doesn't clutter the history no matter how many changes might be required in the PR.

Thanks Jesse. Totally agree on avoiding force pushes. This particular one should be a few mins after the first commit. I thought I can get away with it if I don't get caught by Ben's review labels! :smiley:

File: app/integration_action_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (ilgooz) [reply app/integration_action_test.go]: The new test I have added depends on deferred _tearDown()_.

I agree that the whole situation is ambiguous.

If you would like that, I can revert my changes on [setupMultiPluginApiTest()](https://github.com/mattermost/mattermost-server/pull/13041/files#diff-8a13870e4ccd1878b9c6bae995211f3fR31), don't use it, and just duplicate some code from that for the new test. 

After we figure out the whole situation, we can refactor the test again to get rid of duplicated _setup_ code.

File: plugin/client_rpc.go (hunk 2 above)
Comment (ilgooz) [reply plugin/client_rpc.go]: Hey Christopher, thanks for the review!

For this one, I'm thinking the worst scenarios where we might have some public files/docs are getting pushed with the Webapp and having big binaries for the server. 

I'm also thinking about some scenarios while using this API at _com.mattermost.marketplace-addon_ plugin, since it might need to update 10s or 100s of plugins at the same time (tho, pretty unlikely at this stage) with big sizes, in this case we might get out of memory.

While considering all of these, I think, I prefer to have streams over byte slices. And we already have a few streams in the code base, it feels well adopted to me.

/cc @lieut-data

**Comment by ilgooz** [comment]
~ready for reviews again~

File: app/integration_action_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (lieut-data) [reply app/integration_action_test.go]: Ah, that makes sense. I'd advocate for duplicating the code for new and just revisiting this setup code as it's always been a bit obtuse.

[the remark this answers is not in the document]
Comment (ilgooz) [reply app/integration_action_test.go]: done by 5e71708114c180a966cee941ed54e39bc13e9c23

File: app/plugin_api_test.go [hunk 5]
```diff
@@ -469,6 +471,7 @@ func TestPluginAPILoadPluginConfiguration(t *testing.T) {
 			}
 		]
 	}}`, "testloadpluginconfig", th.App)
+
```
Comment (lieut-data) [inline app/plugin_api_test.go]: nit: can you revert these lines just to avoid unrelated diffs?

File: app/plugin_api_test.go [hunk 6]
```diff
@@ -731,6 +735,127 @@ func TestPluginAPIInstallPlugin(t *testing.T) {
 	assert.True(t, found)
 }
 
+func TestInstallPlugin(t *testing.T) {
+	// TODO(ilgooz): remove this setup func to use existent setupPluginApiTest().
+	// following setupTest() func is a modified version of setupPluginApiTest().
+	// we need a modified version of setupPluginApiTest() because it wasn't possible to use it directly here
+	// since it removes plugin dirs right after it returns, does not update App configs with the plugin
+	// dirs and this behavior tends to brake this test as a result.
```
Comment (lieut-data) [inline app/plugin_api_test.go]:
```suggestion
	// dirs and this behavior tends to break this test as a result.
```

File: app/plugin_api_test.go [hunk 7]
```diff
@@ -731,6 +735,127 @@ func TestPluginAPIInstallPlugin(t *testing.T) {
 	assert.True(t, found)
 }
 
+func TestInstallPlugin(t *testing.T) {
+	// TODO(ilgooz): remove this setup func to use existent setupPluginApiTest().
```
Comment (lieut-data) [inline app/plugin_api_test.go]: 👍

File: app/plugin_api_test.go (hunk 6 above)
Comment (ilgooz) [reply app/plugin_api_test.go]: solved by a24cae9240cf3d0c61fd801c2be3bfc06a22620d

File: app/plugin_api_test.go (hunk 5 above)
Comment (ilgooz) [reply app/plugin_api_test.go]: solved by a24cae9

**Comment by prapti** [comment]
@ilgooz @lieut-data Would it be possible to add detailed test steps since I'm not familiar with RPC calls and how to verify. Thank you!

**Comment by lieut-data** [comment]
@prapti, notwithstanding the RPC nomenclature, there's nothing special here: just need to verify that `InstallPlugin` as an API used by /another/ plugin actually works. Happy to help write some sample code.

(Technically, it looks like we just missed QA Review on the original https://github.com/mattermost/mattermost-server/pull/12232 -- not sure why that one slipped through, but we'll try to be more diligent!)

**Comment by hanzei** [comment]
Thank you very much for fixing this @ilgooz :tada:
