### PR TITLE
Issue #18191 and #18193 fixed

### LINKED ISSUE #18191: Remove all instances of "zz" + model.NewId() in storetest/compliance_store.go
#### Summary
We have typically used "zz" to avoid clashes with random strings while searching for names. The new function to use is `NewTestId`

1. Search for `"zz" + model.NewId()` in storetest/compliance_store.go
2. Replace them with `NewTestId()`

### LINKED ISSUE #18193: Remove all instances of "zz" + model.NewId() in storetest/post_store.go
#### Summary
We have typically used "zz" to avoid clashes with random strings while searching for names. The new function to use is `NewTestId`

1. Search for `"zz" + model.NewId()` in storetest/post_store.go
2. Replace them with `NewTestId()`

### PR DESCRIPTION
**Pull request by amirmoyousefi**
#### Summary

Issue #18191 and #18193 fixed.

Fixes #18191
Fixes #18193 

#### Release Note

```release-note
NONE

```

### CODE REVIEW

File: store/storetest/compliance_store.go [hunk 1]
```diff
@@ -104,7 +104,7 @@ func testComplianceExport(t *testing.T, ss store.Store) {
 
 	t1 := &model.Team{}
 	t1.DisplayName = "DisplayName"
-	t1.Name = "zz" + model.NewId() + "b"
+	t1.Name = NewTestId() + "b"
```
Comment (agnivade) [inline store/storetest/compliance_store.go:107]: Please remove all suffixes like `b`, `a` and others from here and everywhere else as well.

Some tests might fail if it tests for exactly those suffixes, but otherwise we should remove it.

**Comment by agnivade** [comment]
Thank you @amirmoyousefi ! Are you able to sign the CLA? We can go forward with the PR then.

**Review by agnivade — APPROVED** [review]
